name: Publish Intellij Plugin

on:
  push
    
jobs:
  publish_idea_plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
                  
    - name: Install jq for json manipulation
      run: sudo apt-get install jq
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '8.x'

    - name: Set up JDK 1.8
      run: |
        sudo apt-get install wget
        mkdir jdk8-dir
        cd jdk8-dir
        wget http://enos.itcollege.ee/~jpoial/allalaadimised/jdk8/jdk-8u241-linux-x64.tar.gz
        pwd
        sudo tar -xvzf jdk-8u241-linux-x64.tar.gz
        echo 'export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_241' >> ~/.bashrc
        echo 'export PATH=$PATH:/usr/lib/jvm/jdk1.8.0_241/bin' >> ~/.bashrc

    - name: Clone ballerina-lang repo
      run: git clone https://github.com/lasinicl/dummy-plugin-repository-main
          
    - name: Build and publish plugin
      run: |
        version=1.1
        BAL_VERSION="V${version}"
        git checkout $BAL_VERSION
        cd tools-plugin/intellij/
        ./gradlew buildPlugin 
        ./gradlew publishPlugin -PintellijPublishToken=${{ secrets.IDEA_TOKEN }}
