name: Publish Intellij Plugin

on:
  push
    
jobs:
  publish_idea_plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
                  
    - name: Install jq for json manipulation
      run: sudo apt-get install jq
        
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '8.x'

    - name: Set up JDK 1.8
      run: |
        sudo apt-get install wget
        mkdir jdk8-dir
        cd jdk8-dir
        wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u251-b08/3d5a2bb8f8d4428bbe94aed7ec7ae784/jdk-8u251-linux-x64.tar.gz
        JDK_PATH=$PWD
        sudo tar -xvzf jdk-8u241-linux-x64.tar.gz
        echo 'export JAVA_HOME=$PWD/jdk1.8.0_241' >> ~/.bashrc
        echo 'export PATH=$PATH:/jdk1.8.0_241/bin' >> ~/.bashrc
        source ~/.bashrc
        sudo update-alternatives --install "/usr/bin/java" "java" "$JDK_PATH/jdk1.8.0_241/bin/java" 0
        sudo update-alternatives --install "/usr/bin/javac" "javac" "$JDK_PATH/jdk1.8.0_241/bin/javac" 0
        sudo update-alternatives --set java $JDK_PATH/jdk1.8.0_241/bin/java
        sudo update-alternatives --set javac $JDK_PATH/jdk1.8.0_241/bin/javac    
        java -version
        
    - name: Clone ballerina-lang repo
      run: git clone https://github.com/lasinicl/dummy-plugin-repository-main.git

    - name: Build and publish plugin
      run: |
        version=1.2.5
        BAL_VERSION="v${version}"

        cd dummy-plugin-repository-main/tools-plugin/intellij/
        git checkout $BAL_VERSION
        ./gradlew buildPlugin 
        ./gradlew publishPlugin -PintellijPublishToken=${{ secrets.IDEA_TOKEN }}
