on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get ballerina version
      run: |
           BAL_VERSION=dummyBranch
           echo "::set-env name=ballerina_version::$BAL_VERSION"
    - uses: actions/checkout@v2
      with:
        repository: lasinicl/dummy-plugin-repository-main
        ref: $ballerina_version
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with gradle
      run: |
           cd tools-plugin/intellij
           ./gradlew buildPlugin
           ./gradlew publishPlugin
      
